server:
  port: 9080

logging:
  level:
    org.springframework.web: INFO
    org.apache.jmeter: WARN
    org.apache.jmeter.reporters: INFO # Summarizer
    de.datev.loadtest.client: INFO

management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
    enabled-by-default: true
  endpoint:
    health:
      show-details: always


spring:
  # Allow Thymeleaf templates to be reloaded at dev time
  thymeleaf.cache: false

redis:
  host: localhost
  port: 6379

app-config:
  show-config-on-startup: true
  start-running: false
  redis-enabled: true
  redis-purge-on-start: true
  log-output-enabled: true
  log-files-enabled: false
  number-of-threads: 4
  runs-in-one-loop: 10
  initial-delay-milliseconds: 1000
  wait-interval-milliseconds: 100
  poll-interval-milliseconds: 1000
  jmx-file: 'jmx/fib1-only.jmx'
  #jmx-file: 'jmx/fib35-only.jmx'
  #jmx-file: 'jmx/load-mixed-with-remote.jmx'
  #jmx-file: 'jmx/pms-random-read-plain.jmx'
  #csv-files: 'jmx/pms-user-logins.csv,jmx/pms-employee-queries.csv'
  summariser-interval: 30
  target-host: localhost
  target-port: 8080
  target-protocol: http
  #target-host: pmssql.pcfapps.dev.datev.de
  #target-port: 443
  #target-protocol: https

---
# spring profile for paas deployment (=cloud)
# here all configurations are mapped to environment variables generated by paas service brokers
spring:
  profiles: cloud
  # Do not allow Thymeleaf templates to be reloaded at runtime
  thymeleaf.cache: true

logging:
  level:
    org.springframework.web: INFO
    org.apache.jmeter: WARN
    org.apache.jmeter.reporters: WARN # Summarizer
    de.datev.loadtest.client: DEBUG

app-config:
  show-config-on-startup: true
  redis-purge-on-start: false
  number-of-threads: 10
  runs-in-one-loop: 10000
  initial-delay-milliseconds: 5000
  wait-interval-milliseconds: 1000
  jmx-file: 'jmx/fib35-only.jmx'
  #jmx-file: 'jmx/load-mixed-with-remote.jmx'
  summariser-interval: 30